In [1]:
import pandas as pd
from src.cluster_enrichment_analysis import analyze_cluster_deviations

#Import data for 35 K-Means clusters in SPARC IBD using 9 NOD sig genes
SPARC_KMeans_9F_35C_NOD_2_genepy = pd.read_table("C:/Users/fvl1g23/OneDrive - University of Southampton/PhD/Projects/ML/Unsupervised ML/K-Means cluster enrichment analysis/K-Means output/SPARC_KMeans_9F_35C_NOD_2_genepy.txt")
SPARC_KMeans_9F_35C_NOD_2_genepy = SPARC_KMeans_9F_35C_NOD_2_genepy.set_index("Samid")

SPARC_KMeans_9F_21C_NOD_2_genepy = pd.read_table("C:/Users/fvl1g23/OneDrive - University of Southampton/PhD/Projects/ML/Unsupervised ML/K-Means cluster enrichment analysis/K-Means output/SPARC_KMeans_9F_21C_NOD_2_genepy.txt")
SPARC_KMeans_9F_21C_NOD_2_genepy = SPARC_KMeans_9F_21C_NOD_2_genepy.set_index("Samid")

In [2]:
results = analyze_cluster_deviations(SPARC_KMeans_9F_21C_NOD_2_genepy, ['Diagnosis', "Crohn's disease phenotype", "IBD surgery final"])

In [15]:
results['Diagnosis']['corr_p_values_chi2']

Diagnosis        CD        UC
0          0.647511  0.481263
1          0.251921  0.070641
2          0.643129  0.466744
3          0.905677  0.827563
4          0.195277  0.037226
5          0.785781  0.643129
7          0.494391  0.251921
8          0.251921  0.070641
9          0.984815  0.984815
10         0.932931  0.905677
12         0.200633  0.038500
14         0.037226  0.000908
15         0.932931  0.905677
16         0.984815  0.984815
17         0.535236  0.302037
18         0.495179  0.255808
19         0.121900  0.023574
20         0.827563  0.741248
Misc       0.806547  0.656648

In [16]:
results['Diagnosis']['residuals']

Diagnosis        CD        UC
0          0.856151 -1.239118
1          1.723201 -2.494011
2         -0.892356  1.291519
3          0.351944 -0.509373
4          1.993107 -2.884649
5          0.616386 -0.892103
7         -1.189647  1.721791
8         -1.715883  2.483420
9          0.019032 -0.027546
10        -0.218750  0.316600
12        -1.936568  2.802820
14         2.919125 -4.224887
15        -0.208642  0.301970
16         0.067377 -0.097516
17        -1.076501  1.558034
18        -1.156224  1.673417
19         2.231271 -3.229346
20        -0.479531  0.694031
Misc       0.563532 -0.815607

In [22]:
SPARC_KMeans_9F_21C_NOD_2_genepy[(SPARC_KMeans_9F_21C_NOD_2_genepy['Cluster'] == 19) & (SPARC_KMeans_9F_21C_NOD_2_genepy['Diagnosis'] != "IBDU")]['ENSG00000106100_NOD1_CADD15_matrix'].value_counts().sort_index(ascending=False)

ENSG00000106100_NOD1_CADD15_matrix
0.127193     7
0.076267    41
0.000000    65
Name: count, dtype: int64